language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test-headless
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn run build --prod
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  local-dir: dist/shop
  on:
    branch: main
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST